language: "node_js"
node_js:
  - "6"
# cache:
  # npm: false
install:
  - "npm install gitbook"
  - "npm install gitbook-cli@2.3.0"
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/yalezhangk/blog.git
script:
  - bash summary_create.sh
  - travis_wait 100 bash deploy.sh
